In [6]:
import os 
import sys
import glob
import numpy as np
import pandas as pd 
import mne
import matplotlib

In [7]:
matplotlib.use('Qt5Agg')

In [8]:
variableNames = ["EEG FP1", "EEG FP2", "EEG F7", "EEG F3", "EEG Fz", "EEG F4", "EEG F8", "EEG T3", "EEG C3", "EEG Cz", "EEG C4", "EEG T4", "EEG T5", "EEG P3", "EEG PZ", "EEG P4", "EEG T6", "EEG O1", "EEG O2", "EEG A1", "EEG A2", "SensorCEOG", "SensorDEOG"]
variableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"]

initialCols = ['Fp1', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'T3', 'C3', 'Cz', 'C4', 'T4', 'T5', 'P3', 'Pz', 'P4', 'T6', 'O1', 'O2', 'A1', 'A2', "SensorCEOG", "SensorDEOG", "Events"]

columnNames = ['Fp1', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'T3', 'C3', 'Cz', 'C4', 'T4', 'T5', 'P3', 'Pz', 'P4', 'T6', 'O1', 'O2', 'A1', 'A2', "SensorCEOG", "SensorDEOG"]
varlistType = ["eeg", "eeg","eeg","eeg","eeg","eeg","eeg","eeg","eeg","eeg","eeg","eeg","eeg","eeg","eeg","eeg","eeg","eeg","eeg","eeg","eeg","eog", "eog"]

eegFiles = glob.glob("C:/Users/PRASANNA/Desktop/sem9/eeg_project/eegdatafiles/*.txt")

In [9]:
# creating the MNE DS with sampling frequency of 256 hz
sfreq = 256
info = mne.create_info(ch_names=columnNames, sfreq=sfreq)
info

<Info | 7 non-empty values
 bads: []
 ch_names: Fp1, Fp2, F7, F3, Fz, F4, F8, T3, C3, Cz, C4, T4, T5, P3, Pz, ...
 chs: 23 misc
 custom_ref_applied: False
 highpass: 0.0 Hz
 lowpass: 128.0 Hz
 meas_date: unspecified
 nchan: 23
 projs: []
 sfreq: 256.0 Hz
>

In [10]:
# for ind in range(0, len(eegFiles)):

#     fileName = eegFiles[ind]
#     raw = pd.read_csv(fileName,skiprows=0,encoding='latin1')
#     raw.columns = initialCols

#     trig = raw["Events"]
#     trig_names = trig[~np.isnan(trig)]
#     print(trig_names)


In [12]:
ind = 0
fileName = eegFiles[ind]
raw = pd.read_csv(fileName,skiprows=0,encoding='latin1')
# raw.columns = ["EEG FP1", "EEG FP2", "EEG F7", "EEG F3", "EEG Fz", "EEG F4", "EEG F8", "EEG T3", "EEG C3", "EEG Cz", "EEG C4", "EEG T4", "EEG T5", "EEG P3", "EEG PZ", "EEG P4", "EEG T6", "EEG O1", "EEG O2", "EEG A1", "EEG A2", "SensorCEOG", "SensorDEOG", "Events"]
raw.columns = initialCols

# get the trigger names and times if any
trig = raw["Events"]
trig_names = trig[~np.isnan(trig)]
print(trig_names)

# exclude events column from the dataframe
raw = raw.drop(["Events"], axis=1)

# get rid of nans if any (normally the last samples)
raw = raw.dropna()

print(raw.shape)

# converting raw data frame data into MNE raw data
raw = mne.io.RawArray(raw.T, info)

# setting correct channel types
raw.set_channel_types(dict(zip(columnNames, varlistType)))


# adding the FIR and hamming window filter
low_freq, high_freq = 1.0, 40.0 # values in Hz
raw = raw.filter(low_freq, high_freq, picks="all")

# plot the EEG signals 
# raw.plot(block=True)

Series([], Name: Events, dtype: float64)
(1243136, 23)
Creating RawArray with float64 data, n_channels=23, n_times=1243136
    Range : 0 ... 1243135 =      0.000 ...  4855.996 secs
Ready.
Filtering raw data in 1 contiguous segment
Setting up band-pass filter from 1 - 40 Hz

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandpass filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower passband edge: 1.00
- Lower transition bandwidth: 1.00 Hz (-6 dB cutoff frequency: 0.50 Hz)
- Upper passband edge: 40.00 Hz
- Upper transition bandwidth: 10.00 Hz (-6 dB cutoff frequency: 45.00 Hz)
- Filter length: 845 samples (3.301 s)



C:\Users\PRASANNA\AppData\Local\Temp/ipykernel_17004/1159441439.py:24: RuntimeWarning: The unit for channel(s) A1, A2, C3, C4, Cz, F3, F4, F7, F8, Fp1, Fp2, Fz, O1, O2, P3, P4, Pz, SensorCEOG, SensorDEOG, T3, T4, T5, T6 has changed from NA to V.
  raw.set_channel_types(dict(zip(columnNames, varlistType)))
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  23 out of  23 | elapsed:    1.2s finished


In [ ]:
# mne.channels.get_builtin_montages()
# montage = mne.channels.read_custom_montage("./eeglocs.csv", head_size=0.095, coord_frame=None)
# mne.viz.plot_montage(montage)

mont1020 = mne.channels.make_standard_montage('standard_1020')
# Choose what channels you want to keep 
# Make sure that these channels exist e.g. T1 does not exist in the standard 10-20 EEG system!
kept_channels = ['Fp1', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'T3', 'C3', 'Cz', 'C4', 'T4', 'T5', 'P3', 'Pz', 'P4', 'T6', 'O1', 'O2', 'A1', 'A2']
ind = [i for (i, channel) in enumerate(mont1020.ch_names) if channel in kept_channels]
mont1020_new = mont1020.copy()
# Keep only the desired channels
mont1020_new.ch_names = [mont1020.ch_names[x] for x in ind]
kept_channel_info = [mont1020.dig[x+3] for x in ind]
# Keep the first three rows as they are the fiducial points information
mont1020_new.dig = mont1020.dig[0:3]+kept_channel_info
mont1020_new.plot()
raw.set_montage(mont1020_new)

<RawArray | 23 x 1243136 (4856.0 s), ~218.2 MB, data loaded>

In [7]:
# performing ICA
ica = mne.preprocessing.ICA()
ica.fit(raw)

Fitting ICA to data using 21 channels (please be patient, this may take a while)
Selecting by non-zero PCA components: 20 components
Fitting ICA took 56.4s.


<ICA | raw data decomposition, method: fastica (fit in 48 iterations on 1243136 samples), 20 ICA components (21 PCA components available), channel types: eeg, no sources marked for exclusion>

In [9]:
ica.plot_components()

<MNEFigure size 1218.75x1055 with 20 Axes>

In [9]:
from mne_icalabel import label_components

label_components(raw, ica, method='iclabel')

C:\Users\PRASANNA\AppData\Local\Temp/ipykernel_21360/3386525049.py:3: RuntimeWarning: The provided Raw instance does not seem to be referenced to a common average reference (CAR). ICLabel was designed to classify features extracted from an EEG dataset referenced to a CAR (see the 'set_eeg_reference()' method for Raw and Epochs instances).
  label_components(raw, ica, method='iclabel')
C:\Users\PRASANNA\AppData\Local\Temp/ipykernel_21360/3386525049.py:3: RuntimeWarning: The provided Raw instance is not filtered between 1 and 100 Hz. ICLabel was designed to classify features extracted from an EEG dataset bandpass filtered between 1 and 100 Hz (see the 'filter()' method for Raw and Epochs instances).
  label_components(raw, ica, method='iclabel')
C:\Users\PRASANNA\AppData\Local\Temp/ipykernel_21360/3386525049.py:3: RuntimeWarning: The provided ICA instance was fitted with a 'fastica' algorithm. ICLabel was designed with extended infomax ICA decompositions. To use the extended infomax algo

NOTE: pick_channels() is a legacy function. New code should use inst.pick(...).


AttributeError: 'NoneType' object has no attribute 'get_positions'

In [13]:
raw

<RawArray | 23 x 1243136 (4856.0 s), ~218.2 MB, data loaded>

In [8]:
from mne import events_from_annotations, Epochs
from mne.time_frequency import tfr_morlet

events, _ = events_from_annotations(raw, regexp="Stimulus")

In [11]:
data, times = raw[:] 

In [12]:
data = np.array(data)
type(data)

numpy.ndarray

In [13]:
data.shape

(23, 1243136)

In [22]:
math.floor(data.shape[1]/250)*250

1243000

In [25]:
import math 
new_data = data[0:23, 1: (math.floor(data.shape[1]/250)*250) + 1]

In [26]:
new_data.shape

(23, 1243000)

In [30]:
stimulated_epochs = np.reshape(new_data, (250, 23,math.floor(new_data.shape[1]/250) ))

In [31]:
stimulated_epochs.shape


(250, 23, 4972)

In [32]:
stimulated_epochs = mne.EpochsArray(stimulated_epochs, info)

Not setting metadata
250 matching events found
No baseline correction applied
0 projection items activated


In [1]:
stimulated_epochs

NameError: name 'stimulated_epochs' is not defined

In [14]:
fixed_epochs = mne.make_fixed_length_epochs(raw, 5)
fixed_epochs 

Not setting metadata
971 matching events found
No baseline correction applied
0 projection items activated


<Epochs |  971 events (good & bad), 0 – 4.99609 s, baseline off, ~27 kB, data not loaded,
 '1': 971>

In [28]:
from mne.time_frequency import tfr_morlet 

freqs = np.arange(5.,30.,step=0.5)
n_cycles = 4.0
tfr = tfr_morlet(fixed_epochs, freqs, n_cycles, return_itc=False, average=False, picks=[1,2])
print(tfr.data.shape)

Using data from preloaded Raw for 971 events and 1280 original time points ...


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    7.7s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:   15.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:   15.8s finished


Not setting metadata
(971, 2, 50, 1280)


In [29]:
tfr.data.shape

(971, 2, 50, 1280)

In [91]:
psds,frequencies = mne.time_frequency.psd_array_welch(fixed_epochs.get_data(), fmin = 8, fmax = 12, n_fft=128, n_overlap=0, n_per_seg=None, average='mean', window='hamming', verbose=None, sfreq=256) # alpha band as from 8 to 12

print(psds)
print(frequencies)

Using data from preloaded Raw for 971 events and 1280 original time points ...
Effective window size : 0.500 (s)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[[[1.03776415e+03 8.34342641e+02 6.98203473e+02]
  [8.92482610e+02 7.34391971e+02 6.07246376e+02]
  [6.17047655e+02 5.29004301e+02 4.27562342e+02]
  ...
  [1.42024095e+01 1.59926662e+01 1.16152575e+01]
  [2.81142466e+00 1.69264469e+00 2.69733936e+00]
  [1.35324986e+00 8.40685413e-01 4.86619695e-01]]

 [[1.30009572e+00 4.09605911e-01 3.09252530e-01]
  [1.01436428e+01 8.47200566e+00 5.11129502e+00]
  [3.84084205e+00 2.11323684e-01 2.36818677e-01]
  ...
  [3.01487978e+00 2.49415649e+00 2.31510451e+00]
  [2.37259913e+00 1.85874267e+00 1.57020950e+00]
  [2.54431811e+00 1.18798561e+00 1.17823983e+00]]

 [[1.38946166e+00 1.79270685e-01 2.57958053e-01]
  [1.49558357e+00 5.88529876e-01 6.92528693e-01]
  [3.73065489e+00 3.64183181e-01 2.39309448e-01]
  ...
  [1.25071429e+00 9.71245626e-01 4.23749311e-01]
  [1.55413416e+00 1.30750702e+00 1.56487302e+00]
  [2.62879306e+00 1.96184284e+00 9.20649865e-01]]

 ...

 [[7.20107687e-01 2.57010407e-01 1.90233859e-01]
  [9.42846968e-01 3.54503514e-01 2.8744

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    8.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    8.2s finished


In [92]:
a_mean = np.array(psds)

In [93]:
a_mean.shape

(971, 23, 3)

In [56]:
count

2